import {
  BLOG_SCREEN,
  BLOG_STACK,
  DETAIL_COURSE_SCREEN,
  DETAIL_LIVE_CLASS_SCREEN,
  DRAWER_STACK,
  HOME_SCREEN,
  HOME_TAB_NAVIGATOR,
  LIST_COURSE_SCREEN,
  // LIST_COURSE_STACK,
  LIVE_CLASS_SCREEN,
  LIVE_CLASS_STACK,
  MY_COURSE_SCREEN,
  PROFILE_SCREEN,
  TEMPLATE_SCREEN,
} from 'src/navigation/screen';

import { isTablet } from './Constants';

export const LIST_LANGUAGE = ['', '', 'Tiếng việt', 'US English', '', ''];

// export const LIST_DRAWER = [
//   {
//     id: 0,
//     name: 'MENU',
//     icon: 'app-icon',
//   },
//   {
//     id: 1,
//     name: 'MY_COURSE',
//     icon: 'book-2',
//     screen: MY_COURSE_SCREEN,
//     childrenScreen: [
//       HOME_TAB_NAVIGATOR,
//       HOME_SCREEN,
//       MY_COURSE_SCREEN,
//       DETAIL_COURSE_SCREEN,
//       DRAWER_STACK,
//     ],
//   },
//   {
//     id: 2,
//     name: 'LIST_COURSE',
//     icon: 'book-1',
//     screen: isTablet ? LIST_COURSE_SCREEN : LIST_COURSE_STACK,
//     childrenScreen: [LIST_COURSE_SCREEN, LIST_COURSE_STACK],
//   },
//   {
//     id: 3,
//     name: 'GO_EDU_LIVE_CLASS',
//     icon: 'tivi-icon',
//     screen: isTablet ? LIVE_CLASS_SCREEN : LIVE_CLASS_STACK,
//     childrenScreen: [
//       LIVE_CLASS_SCREEN,
//       LIVE_CLASS_STACK,
//       DETAIL_LIVE_CLASS_SCREEN,
//     ],
//   },
//   {
//     id: 4,
//     name: 'BLOG',
//     icon: 'carbon-blog',
//     screen: isTablet ? BLOG_SCREEN : BLOG_STACK,
//     childrenScreen: [BLOG_SCREEN, BLOG_STACK],
//   },
//   {
//     id: 5,
//     name: 'TEMPLATE_LIBRARY',
//     icon: 'image-icon',
//     screen: TEMPLATE_SCREEN,
//     childrenScreen: [TEMPLATE_SCREEN],
//   },
//   {
//     id: 6,
//     name: 'PERSONAL_INFORMATION',
//     icon: 'contact-icon',
//     screen: PROFILE_SCREEN,
//     childrenScreen: [PROFILE_SCREEN],
//   },
//   {
//     id: 7,
//     name: 'LOGOUT',
//     icon: 'logout-icon',
//   },
// ];

// export const LIST_COURSE = [
//   {
//     title: 'Cơ bản',
//     data: [],
//   },
//   {
//     title: 'Nâng cao',
//     data: [],
//   },
//   {
//     title: 'Chuyên gia',
//     data: [],
//   },
// ];

// export const LIST_COURSE_TABLET = [
//   {
//     title: 'Cơ bản',
//     data: [{ data: [1, 1, 4, 4] }],
//   },
//   {
//     title: 'Nâng cao',
//     data: [{ data: [1, 1, 4, 4, 4] }],
//   },
//   {
//     title: 'Chuyên gia',
//     data: [{ data: [1, 1, 2, 3] }],
//   },
// ];

// export const LIST_TYPE_LIST_COURSE = [
//   { id: 0, name: 'ALL' },
//   { id: 1, name: 'Cơ bản' },
//   { id: 2, name: 'Nâng cao' },
//   { id: 3, name: 'Chuyên gia' },
// ];

export const FORM_REGISTER = [
  {
    id: 0,
    title: 'STUDENT_CODE',
    placeholder: 'ENTER_STUDENT_CODE',
    key: 'studentCode',
  },
  {
    id: 1,
    title: 'NAME',
    placeholder: 'ENTER_NAME',
    key: 'name',
  },
  {
    id: 2,
    title: 'EMAIL_LOGIN',
    placeholder: 'ENTER_EMAIL',
    key: 'email',
  },
  {
    id: 3,
    title: 'PASSWORD',
    placeholder: 'ENTER_PASSWORD',
    key: 'password',
    security: true,
  },
  {
    id: 4,
    title: 'RE_PASSWORD',
    placeholder: 'RE_ENTER_PASSWORD',
    key: 'confirmPassword',
    security: true,
  },
  {
    id: 5,
    title: 'OTP',
    placeholder: 'ENTER_OTP',
    key: 'otp',
  },
];
export const FORM_SEND_OTP = [
  { id: 0, title: 'EMAIL_LOGIN', placeholder: 'ENTER_EMAIL', key: 'email' },
  {
    id: 1,
    title: 'STUDENT_CODE',
    placeholder: 'ENTER_STUDENT_CODE',
    key: 'studentCode',
  },
];

export const DATA_CALENDER = [
  {
    day: '10/01/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '11/01/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '12/01/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '13/01/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '17/01/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '18/01/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '19/01/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '20/01/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '07/02/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '08/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '09/02/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '10/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '14/02/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '15/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '16/02/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '17/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '18/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '21/02/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '22/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '24/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '25/02/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '28/02/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '01/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '03/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '07/03/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '08/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '10/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '14/03/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '15/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '17/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '21/03/2022',
    subjectCode: 'CTCTHT9',
    subjectName: 'Thiết kế hệ thống nhúng',
    className: 'Thiết kế hệ thống nhúng-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '22/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '24/03/2022',
    subjectCode: 'CTCTHT17',
    subjectName: 'Lập trình nhân Linux',
    className: 'Lập trình nhân Linux-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '04/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '06/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '07/04/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '08/04/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '12/04/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '13/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '14/04/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '18/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '20/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '21/04/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '22/04/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '25/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '27/04/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '28/04/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '29/04/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '04/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '05/05/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '06/05/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '09/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '11/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '',
  },
  {
    day: '12/05/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '13/05/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '16/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '18/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '19/05/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03)',
    teacher: 'Lê Bá Cường',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '20/05/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03)',
    teacher: 'Cao Thanh Vinh',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '23/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '25/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '26/05/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '27/05/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '30/05/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '01/06/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '02/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '03/06/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '06/06/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '08/06/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '09/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '10/06/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '13/06/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '15/06/2022',
    subjectCode: 'CTCTHT18',
    subjectName: 'Lập trình driver',
    className: 'Lập trình driver-2-21 (C303.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '16/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '17/06/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '21/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '22/06/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '23/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '24/06/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '28/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '29/06/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '30/06/2022',
    subjectCode: 'CTCTKM10',
    subjectName: 'Lập trình Android cơ bản (có thể thay thế)',
    className: 'Lập trình Android cơ bản (có thể thay thế)-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
  {
    day: '01/07/2022',
    subjectCode: 'CTCTKM14',
    subjectName: 'Phát triển phần mềm trong thẻ thông minh',
    className: 'Phát triển phần mềm trong thẻ thông minh-2-21 (C3D03.1)',
    teacher: '',
    lesson: '13,14,15,16',
    room: '601-TA3(DĐ)-CNTT TA3',
  },
];
